// This file is auto-generated by tools/generate-i18n-resources.ts
// Do not edit this file directly

export const resources = {
  en: {
    translation: {
      common: {
        theme: {
          toggle: "Toggle Theme",
          toggle_aria_label: "Toggle theme",
          light: "Light",
          dark: "Dark",
          system: "System"
        },
        bug_report: {
          label: "Bug",
          aria_label: "Report a bug or request a feature",
          tooltip: "Report a bug or request a feature"
        },
        settings: {
          label: "Setting",
          aria_label: "Extension Settings",
          tooltip: "Extension Settings"
        },
        actions: {
          retry: "Retry",
          refresh: "Refresh"
        },
        social: {
          title: "Connect With Me",
          visit_profile: "Visit my {{platform}} profile"
        },
        language: {
          label: "Language",
          select_label: "Interface Language",
          beta_badge: "Beta",
          description: "Select your preferred language for the interface.",
          help_text:
            "Translations are AI-generated. Help us improve by contributing on <0>GitHub</0>!"
        }
      },
      selection_button: {
        label: "Ask Ollama client",
        tooltip: "Add to Ollama Client"
      },
      welcome: {
        title: "Welcome to Ollama Chat",
        subtitle: "Local AI conversations made simple",
        start_chatting: "Start Chatting",
        status: {
          connecting: {
            title: "Connecting...",
            message: "Establishing connection to Ollama server"
          },
          connection_failed: {
            title: "Connection Failed",
            message: "Failed to connect to Ollama. Is the server running?"
          },
          no_models: {
            title: "No Models Found",
            message: "Please pull a model to get started"
          },
          ready: {
            title: "Ready to Chat",
            message: "Ollama is connected and ready to use"
          }
        },
        setup_guide: {
          intro: "Before you start, follow these quick steps:",
          step1: "Install <code>ollama</code> on your system",
          step2: "Run <code>ollama run llama3</code> or any model",
          step3: "Return here and click <b>Refresh</b>",
          full_guide_link: "Full Setup Guide"
        },
        features: {
          private: {
            title: "100% Private",
            description: "Your data stays local"
          },
          offline: {
            title: "Works Offline",
            description: "No internet needed"
          },
          local_processing: {
            title: "Local Processing",
            description: "Full control"
          },
          embeddings: {
            title: "Vector Embeddings",
            description: "Semantic search ready"
          }
        },
        performance_notice: {
          title: "⚠️ Performance Notice",
          message:
            "This extension is a user interface for your local Ollama server. Response time and model output quality depend entirely on your device's hardware (CPU, RAM, GPU) and the specific model you're using. No processing is done by the extension itself."
        }
      },
      chat: {
        input: {
          placeholder: "Type a message...",
          switch_model: "Change model",
          files_ready: "There are {{count}} files ready.",
          chars: "Characters",
          enter_to_send: "Send",
          enter_key: "Enter"
        },
        actions: {
          copy: "Copy",
          copied: "Copied",
          regenerate: "Regenerate",
          switch_model_tooltip: "Switch model"
        },
        metrics: {
          title: "Performance Metrics",
          toggle_aria_label: "Toggle metrics",
          toggle_title: "Toggle metrics",
          total_time: "Total Time",
          generation_speed: "Generation Speed",
          prompt_tokens: "Prompt Tokens",
          generated_tokens: "Generated Tokens",
          load_time: "Load Time",
          prompt_eval_time: "Prompt Eval Time"
        },
        search: {
          button_title: "Search chat history (semantic search)",
          button_label: "Search Chats",
          dialog_title: "Semantic Chat Search",
          dialog_description:
            "Search your chat history by meaning, not just keywords",
          beta_badge: "Beta v0.3.0",
          placeholder: "Search conversations by meaning...",
          scope_all: "All Chats",
          scope_current: "Current Chat",
          searching: "Searching chat history...",
          no_results: "No results found. Try a different search query.",
          start_typing:
            "Start typing to search your chat history semantically...",
          result_badge: "result",
          results_badge: "results",
          match_percentage: "% match",
          role_you: "You",
          role_assistant: "Assistant",
          unknown_session: "Unknown Session",
          time_just_now: "Just now",
          time_minute: "minute",
          time_minutes: "minutes",
          time_hour: "hour",
          time_hours: "hours",
          time_day: "day",
          time_days: "days",
          time_ago: "ago",
          time_unknown: "Unknown time"
        },
        backfill: {
          title: "Backfill Chat History",
          description:
            "Generate embeddings for all existing chat messages to enable semantic search",
          error_label: "Error",
          completed_label: "Completed!",
          completed_message:
            "Successfully embedded {{current}} messages across {{count}} sessions.",
          processing_label: "Processing {{current}} of {{total}} messages",
          info_sessions:
            "• This will process all messages from {{count}} {{sessions}}",
          session_singular: "session",
          session_plural: "sessions",
          info_min_chars:
            "• Only messages with at least 10 characters will be embedded",
          info_time_warning:
            "• This may take a while depending on the number of messages",
          button_processing: "Processing...",
          button_start: "Start Backfill",
          button_completed: "Backfill Completed"
        },
        send: {
          send_message: "Send message",
          stop_generation: "Stop generation"
        },
        speech: {
          loading_voices: "Loading voices...",
          stop_speaking: "Stop speaking",
          speak_message: "Speak message"
        },
        voice_selector: {
          select_voice: "Select voice",
          select_placeholder: "Select a voice...",
          search_placeholder: "Search by name, language, or URI...",
          no_voices_found: "No voices found",
          no_voices_available: "No voices available on this device",
          try_different_search: "Try a different search term",
          network_voice: "Network voice",
          default_badge: "default",
          unknown_language: "Unknown"
        },
        message: {
          loading: "Loading..."
        }
      },
      file_upload: {
        button: {
          aria_label: "Upload file",
          tooltip: "Upload file (PDF, DOCX, Text files)"
        },
        preview: {
          remove_aria_label: "Remove file",
          generating_embeddings: "Generating embeddings...",
          extracting_pdf: "Extracting text from PDF...",
          processing_docx: "Processing DOCX document...",
          processing_file: "Processing file..."
        },
        area: {
          files_ready: "{{count}} file ready",
          files_ready_plural: "{{count}} files ready"
        },
        settings: {
          max_file_size_label: "Maximum File Size (MB)",
          max_file_size_description:
            "Maximum allowed size for individual files. Larger files may take longer to process."
        }
      },
      model: {
        ollama_status: {
          checking: "Checking Ollama status...",
          error: "Ollama not reachable",
          empty: "No models found",
          ready: "Ollama is ready"
        },
        embedding_status: {
          checking: "Checking status...",
          downloading: "Downloading {{model}}... {{progress}}",
          ready: "Embedding model ready: {{model}}",
          missing: "Model missing: {{model}}",
          checking_model: "Checking embedding model...",
          required_for_rag: "The embedding model is required for RAG features.",
          download_button: "Download Model"
        },
        menu: {
          select_placeholder: "Select model...",
          models_label: "Models",
          refresh_aria_label: "Refresh models",
          refresh_tooltip: "Refresh models",
          search_placeholder: "Search model...",
          no_model_found: "No model found."
        },
        version: {
          tooltip: "Ollama version: {{version}}"
        },
        site_overrides: {
          title: "Site-Specific Overrides",
          description:
            "Configure custom extraction settings for specific sites using regex patterns",
          add_pattern_label: "Add Site Pattern",
          pattern_placeholder: "medium.com or ^https://twitter\\.com/.*",
          pattern_empty_error: "Site pattern cannot be empty",
          pattern_exists_error: "Site override already exists",
          pattern_invalid_error: "Invalid regular expression pattern",
          examples:
            "Examples: <0>medium.com</0> or <0>^https://twitter\\.com/.*</0>",
          active_overrides: "Active Overrides",
          site_count: "{{count}} site",
          site_count_plural: "{{count}} sites",
          select_site_label: "Select Site to Configure",
          select_placeholder: "Select a site...",
          search_placeholder: "Search sites...",
          no_sites_found: "No sites found.",
          no_overrides: "No site-specific overrides configured",
          no_overrides_hint:
            "Add patterns to customize extraction settings for specific sites",
          scroll_strategy_label: "Scroll Strategy",
          scroll_depth_label: "Scroll Depth",
          add_button: "Add"
        },
        exclude_urls: {
          title: "Excluded URLs",
          description:
            "Block extension access from sensitive pages using regex patterns",
          add_pattern_label: "Add URL Pattern",
          pattern_placeholder: "^https://example\\.com/private.*",
          pattern_empty_error: "Pattern cannot be empty",
          pattern_exists_error: "Pattern already exists",
          pattern_invalid_error: "Invalid regular expression pattern",
          examples:
            "Use regular expressions to match URLs. Examples: <0>^https://bank\\.</0> or <0>.*\\.private\\..*</0>",
          active_patterns: "Active Patterns",
          pattern_count: "{{count}} pattern",
          pattern_count_plural: "{{count}} patterns",
          no_patterns: "No URL patterns configured",
          default_badge: "default",
          add_button: "Add"
        },
        embedding_config: {
          storage_stats_title: "Storage Statistics",
          total_vectors: "Total Vectors",
          storage_used: "Storage Used",
          cache: "Cache",
          cache_entries: "{{size}} / {{maxSize}} entries",
          database_management_title: "Database Management",
          database_management_description:
            "Clean up and manage your vector embeddings database",
          remove_duplicates_button: "Remove Duplicates",
          remove_duplicates_description:
            "Remove duplicate embeddings, keeping only the first occurrence of each unique message",
          clear_chat_button: "Clear All Chat Embeddings",
          clear_chat_description:
            "Delete all chat embeddings. You can backfill later to regenerate them",
          clear_all_button: "Clear All Embeddings",
          clear_all_description:
            "Delete all embeddings (chats, files, webpages). This action cannot be undone",
          chunking_title: "Chunking Settings",
          chunking_description:
            "Configure how text is split into chunks for embedding",
          chunk_size_label: "Chunk Size (tokens)",
          chunk_size_description:
            "Number of tokens per chunk. Larger chunks preserve more context but may be less focused.",
          chunk_overlap_label: "Chunk Overlap (tokens)",
          chunk_overlap_description:
            "Overlap between chunks. Helps preserve context across chunk boundaries.",
          chunking_strategy_label: "Chunking Strategy",
          chunking_strategy_description:
            "How to split text into chunks. Hybrid provides the best balance of context and focus.",
          strategy_fixed: "Fixed Size",
          strategy_semantic: "Semantic Boundaries",
          strategy_hybrid: "Hybrid (Recommended)",
          embedding_gen_title: "Embedding Generation",
          embedding_gen_description:
            "Configure embedding generation performance",
          batch_size_label: "Batch Size",
          batch_size_description:
            "Number of texts to embed in parallel. Higher values are faster but use more memory.",
          enable_caching_label: "Enable Caching",
          enable_caching_description:
            "Cache embeddings for identical content to avoid regenerating",
          use_webworker_label: "Use Web Worker",
          use_webworker_description:
            "Offload embedding generation to background thread (recommended)",
          limits_title: "Limits & Storage",
          limits_description: "Configure storage limits and cleanup policies",
          max_embeddings_label: "Max Embeddings Per File",
          max_embeddings_description:
            "Maximum embeddings per file (0 = unlimited). Helps prevent memory issues with very large files.",
          max_storage_label: "Max Storage Size (MB)",
          max_storage_description:
            "Maximum storage size in MB (0 = unlimited). Oldest vectors will be deleted when limit is reached.",
          auto_cleanup_label: "Auto Cleanup",
          auto_cleanup_description: "Automatically delete old embeddings",
          cleanup_age_label: "Cleanup Age (days)",
          cleanup_age_description:
            "Delete embeddings older than this many days",
          chat_search_title: "Chat Search Settings",
          chat_search_description: "Configure semantic search for chat history",
          auto_embed_label: "Auto-embed Chat Messages",
          auto_embed_description:
            "Automatically embed chat messages for semantic search (recommended)",
          backfill_title: "Backfill Chat History",
          backfill_description:
            "Generate embeddings for all existing chat messages to enable semantic search",
          search_settings_title: "Search Settings",
          search_settings_description: "Default parameters for semantic search",
          search_limit_label: "Default Search Limit",
          search_limit_description:
            "Default number of results to return from semantic search",
          min_similarity_label: "Minimum Similarity Threshold",
          min_similarity_description:
            "Minimum cosine similarity score (0-1). For semantic search, 0.4-0.6 is recommended. Higher values return more relevant but fewer results.",
          cache_ttl_label: "Search Cache TTL (minutes)",
          cache_ttl_description:
            "How long to cache search results (1-60 minutes). Cached queries return instantly.",
          cache_max_size_label: "Max Cached Queries",
          cache_max_size_description:
            "Maximum number of search queries to cache (10-200). Older entries are automatically removed when limit is reached."
        }
      },
      prompts: {
        selector: {
          title: "Prompt Templates",
          description:
            "Choose from {{count}} templates to jump start your conversation",
          search_placeholder: "Search templates, tags, or descriptions...",
          sort_recent: "Recent",
          sort_popular: "Popular",
          sort_alphabetical: "A-Z",
          all_categories: "All Categories",
          no_templates_title: "No templates found",
          no_templates_search: "Try adjusting your search or filter criteria",
          no_templates_empty:
            "No prompt templates are available. Create your first template in settings.",
          clear_filters: "Clear filters",
          preview_system_prompt: "System Prompt",
          preview_user_prompt: "User Prompt",
          preview_tags: "Tags",
          use_template: "Use Template",
          copy: "Copy"
        }
      },
      sessions: {
        selector: {
          title: "Chat Sessions",
          create_new: "Create New Chat",
          create_new_aria: "Create New Chat",
          start_new: "Start New Chat",
          no_sessions: "No chat sessions yet",
          no_sessions_hint: "Create your first chat to get started",
          session_count: "{{count}} session",
          session_count_plural: "{{count}} sessions"
        },
        delete: {
          aria_label: "Delete chat session: {{title}}",
          tooltip: "Delete chat"
        },
        export: {
          tooltip: "Export chat",
          tooltip_all: "Export all chat sessions",
          aria_label: "Export chat",
          aria_label_all: "Export all chat sessions",
          format_json: "JSON",
          format_pdf: "PDF"
        },
        import: {
          tooltip: "Import chat sessions",
          aria_label: "Import chat sessions"
        }
      },
      tabs: {
        select: {
          placeholder: "Select open tabs"
        },
        toggle: {
          label_off: "Tabs",
          label_on: "Tab+",
          tooltip: "Interact with open tabs"
        }
      },
      settings: {
        content_extraction: {
          title: "Content Extraction",
          description:
            "Configure default content extraction behavior for all websites.",
          enable: {
            label: "Allow content extraction",
            description:
              "Enable enhanced content extraction with lazy loading support"
          },
          selection_button: {
            label: 'Show "Ask Ollama Client" button after selection',
            description:
              "Show a floating action button when selecting text to speed up adding it to chat"
          },
          scraper: {
            label: "Content Scraper",
            auto: {
              label: "Auto",
              description: "Smart fallback: Defuddle then Readability",
              detail:
                "Good for most sites. Uses Defuddle first for improved markdown and code formatting, falls back to Readability if necessary."
            },
            defuddle: {
              label: "Defuddle",
              description: "Technical and highly coded content",
              detail:
                "Best for GitHub, documentation, Stack Overflow, and developer blogs. Preserves code blocks and markdown structure."
            },
            readability: {
              label: "Readability",
              description: "Articles and blog posts",
              detail:
                "Suitable for news articles, Medium posts, and traditional blog content."
            }
          },
          scroll_strategy: {
            label: "Scroll Strategy",
            none: "Fastest extraction, lazy loading not supported",
            instant: "Fast scrolling works well for simple lazy loading",
            gradual:
              "Balanced smooth scrolling with deliberate pauses and a mix of speed and precision",
            smart: "Dynamic content-aware smart scrolling",
            options: {
              none: "No scrolling",
              instant: "Fast scrolling",
              gradual: "Gradual scrolling",
              smart: "Smart detection"
            },
            options_short: {
              none: "None",
              instant: "Instant",
              gradual: "Gradual",
              smart: "Smart"
            }
          },
          scroll_depth: {
            label: "Scroll Depth",
            description:
              "Percentage of page to scroll (higher = more content, slower)"
          },
          timeout: {
            scroll_delay: "Scroll delay in milliseconds",
            mutation_timeout: "Mutation Observer timeout in milliseconds",
            network_timeout: "Network idle timeout in milliseconds",
            max_wait: "Maximum wait time (milliseconds)"
          },
          badges: {
            recommended: "Recommended",
            active: "Active"
          }
        },
        model: {
          title: "Model Settings",
          description: "Configure parameters for optimal performance.",
          configuration_title: "Model Configuration",
          configuration_description: "Configure your AI model parameters.",
          system: {
            title: "System Configuration",
            description:
              "Configure system prompts and stop sequences to control model behavior.",
            prompt_label: "System Prompt",
            prompt_placeholder:
              "Enter a custom system prompt to guide the model's behavior...",
            stop_sequences_label: "Stop Sequences",
            stop_sequence_placeholder: "Enter stop sequence...",
            add_button: "Add"
          },
          sampling: {
            title: "Sampling Parameters",
            description: "Control randomness and token selection."
          },
          context: {
            title: "Context and Generation",
            description: "Memory and Output Control Settings"
          },
          parameters: {
            temperature: {
              label: "Temperature",
              conservative: "Conservative",
              creative: "Creative"
            },
            top_p: {
              label: "Top-p (nucleus)",
              focused: "Focused",
              diverse: "Diverse"
            },
            top_k: {
              label: "Top-k",
              validation_min: "Must be at least {{min}}"
            },
            min_p: {
              label: "Min-p",
              validation_min: "Must be at least {{min}}.",
              validation_max: "Must be at most {{max}}."
            },
            seed: {
              label: "Seed",
              validation_min: "Must be at least {{min}}"
            },
            num_ctx: {
              label: "Context Size",
              validation_min: "Must be at least {{min}}"
            },
            num_predict: {
              label: "Maximum Tokens",
              validation_min: "Must be at least {{min}}."
            },
            repeat_penalty: {
              label: "Repeat Penalty",
              validation_min: "Must be greater than {{min}}."
            },
            repeat_last_n: {
              label: "Repeat Last N",
              validation_min: "Must be at least {{min}}."
            }
          }
        },
        base_url: {
          title: "Ollama Base URL",
          description:
            "Configure the server endpoint for your Ollama installation.",
          label: "Ollama API Server Endpoint",
          error_invalid_url: "Please enter a valid URL.",
          status_local: "Local server connection",
          status_remote: "Remote server connection",
          badges: {
            default: "Default",
            remote: "Remote"
          },
          button: {
            save: "Save",
            saving: "Saving",
            saved: "Saved"
          }
        },
        model_pull: {
          title: "Model Library",
          description: "Browse and download AI models for your projects.",
          search_placeholder: "Search for models by name or description...",
          status: {
            cancelled: "Cancelled",
            downloading: "Downloading model",
            loading_models: "Loading models...",
            no_models: "No models found",
            adjust_search: "Adjust your search terms."
          },
          button: {
            variants: "Variants",
            loading: "Loading",
            pulling: "Pulling"
          },
          variants_label: "Available Variants"
        },
        model_list: {
          unknown_size: "Unknown size",
          invalid_size: "Invalid size",
          unknown_date: "Unknown date",
          invalid_date: "Invalid date",
          time_ago_hours: "{{count}} hours ago",
          time_ago_days: "{{count}} days ago",
          title: "Models",
          title_count: "{{count}} Models",
          retry: "Retry",
          refresh: "Refresh",
          no_models: "No models found",
          refresh_tooltip: "Refresh models",
          delete_dialog: {
            title: "Delete this model?",
            description:
              "This action cannot be undone. The model will be permanently removed from your local system.",
            cancel: "Cancel",
            confirm: "Delete"
          }
        },
        model_info: {
          title: "Model Information",
          no_data: "No data available for this model.",
          no_data_available: "No model data available",
          error_fetching: "Error fetching model data.",
          error_details: "Could not retrieve model details.",
          refresh_tooltip: "Refresh model details",
          capabilities: "Capabilities",
          technical_details: "Technical Details",
          unknown_file_type: "Unknown"
        },
        loaded_models: {
          title: "Loaded Models",
          count_one: "{{count}} model",
          count_other: "{{count}} models",
          refresh_tooltip: "Refresh loaded models",
          no_models_title: "No models currently loaded in memory",
          no_models_description: "Models will appear here when loaded.",
          unload_tooltip: "Unload model"
        },
        tabs: {
          general: "General",
          prompts: "Prompts",
          models: "Models",
          extraction: "Extraction",
          embeddings: "Embeddings",
          voices: "Voices",
          reset: "Reset",
          guides: "Guides"
        },
        page: {
          title: "Ollama Client Settings",
          description:
            "Manage all aspects of your Ollama setup in one place. For tips and setup guidance, visit the Guides tab."
        },
        speech: {
          title: "Speech Settings",
          description:
            "Configure your text-to-speech voice, speed, and tone settings.",
          voice_label: "Voice",
          rate_label: "Speech Rate",
          pitch_label: "Voice Pitch",
          preview_title: "Preview",
          test_text_label: "Test Text",
          test_text_placeholder: "Test your voice settings by typing here...",
          test_hint_text: 'Click "Test Voice" to hear your text.',
          test_hint_default: 'Click "Test Voice" to hear the default sample.',
          test_button: "Test Voice",
          test_fallback: "Hello, this is a test of your speech settings.",
          rate: {
            very_slow: "Very Slow",
            slow: "Slow",
            normal: "Normal",
            fast: "Fast",
            very_fast: "Very Fast"
          },
          pitch: {
            very_low: "Very Low",
            low: "Low",
            normal: "Normal",
            high: "High",
            very_high: "Very High"
          }
        },
        embeddings: {
          title: "Vector Embeddings",
          beta_badge: "Beta",
          description:
            "Embeddings enable semantic search, retrieval augmented generation, and context-aware features for file uploads and chat history.",
          model_label: "Embedding Model",
          status: {
            installed: "Installed",
            not_found: "Not found",
            checking: "Checking...",
            check_button: "Check Status"
          },
          not_loaded: {
            title: "Embedding model not loaded",
            description:
              "The embedding model is required for semantic search, RAG (Retrieval Augmented Generation), and context-aware features. Download it now to enhance your chat experience with better context understanding and file search capabilities.",
            download_button: "Download Model"
          },
          downloading: {
            title: "Downloading model..."
          },
          success: {
            title: "Download successful",
            description:
              "The embedding model is now ready to use. You can now enjoy enhanced chat experiences with semantic search and context-aware features."
          },
          auto_downloaded: {
            title: "Auto-installed",
            description:
              "The embedding model was automatically downloaded when you installed the extension."
          },
          test_generation: {
            title: "Test Embedding Generation",
            description:
              "Generate a test embedding to verify the embedding model is working correctly.",
            button: "Test",
            button_testing: "Testing..."
          },
          test_search: {
            title: "Semantic Search",
            description:
              "Verify your uploaded files are accessible and searchable. Enter a search query to find matching content.",
            placeholder: "Search...",
            results_found: "Found {{count}} results",
            no_results:
              "No results found. Try a different search or upload more content."
          },
          what_are_embeddings: {
            title: "What are Embeddings?",
            point_1:
              "Convert text into numerical vectors that capture semantic meaning",
            point_2:
              "Enable semantic search across your chat history and uploaded files",
            point_3: "Power RAG for context-aware responses",
            point_4:
              "Provide relevant context from your files to improve AI responses"
          },
          rag_mode: {
            label: "Smart Context (RAG)",
            description:
              "Use semantic search to find relevant context from your files instead of sending the entire file content."
          },
          model_select: {
            label: "Embedding Model",
            placeholder: "Select a model",
            description:
              "Choose a model to generate embeddings. You may need to download it first."
          }
        },
        prompts: {
          title: "Prompt Templates",
          description: "Manage your collection of {{count}} prompt templates.",
          export: "Export Templates",
          import: "Import Templates",
          reset: "Reset to Defaults",
          reset_dialog: {
            title: "Reset templates to defaults?",
            description:
              "This will replace all of your current templates with the default ones. This action cannot be undone.",
            cancel: "Cancel",
            confirm: "Reset Templates"
          },
          search_placeholder: "Search templates...",
          category_placeholder: "Category",
          all_categories: "All Categories",
          sort: {
            recent: "Recent",
            popular: "Popular",
            alphabetical: "A-Z"
          },
          new_template: "New Template",
          form: {
            title: "Title",
            title_placeholder: "Template title",
            category: "Category",
            category_placeholder: "e.g., Development, Writing",
            description: "Description",
            description_placeholder:
              "A brief description of the template's purpose and functionality.",
            tags: "Tags",
            tags_placeholder: "tag1, tag2, tag3",
            user_prompt: "User Prompt",
            user_prompt_placeholder: "Main prompt template",
            system_prompt: "System Prompt",
            create_button: "Create Template"
          },
          delete_dialog: {
            title: "Delete template",
            description:
              'Are you sure you want to delete "{{title}}"? This action cannot be undone.',
            cancel: "Cancel",
            confirm: "Delete"
          },
          created_at: "Created {{date}}",
          used_times: "Used {{count}} times"
        },
        reset: {
          title: "Reset Settings",
          description:
            "Clear stored data by module or reset everything to defaults",
          danger_zone: {
            title: "Danger Zone",
            description: "This will clear all data and cannot be undone",
            button: "Reset All"
          },
          dialog: {
            title: "Confirm Reset",
            description: "This will clear all data and cannot be undone.",
            confirm: "Yes, Reset All",
            cancel: "Cancel"
          },
          modules: {
            ollama: {
              description: "Model settings & configurations"
            },
            theme: {
              description: "UI appearance preferences"
            },
            browser: {
              description: "Tab access & URL patterns"
            },
            tts: {
              description: "Text-to-speech settings"
            },
            chat_sessions: {
              description: "Conversation history"
            },
            default: {
              description: "Module settings"
            }
          },
          item_count: "{{count}} item",
          item_count_plural: "{{count}} items",
          reset_button: "Reset"
        }
      },
      guides: {
        title: "Helpful Guides & Documentation",
        description:
          "Need help setting up Ollama Client or exploring features? Check out these useful resources",
        support: {
          title: "Support the Project",
          description:
            "Help us grow by featuring Ollama Client on Product Hunt",
          image_alt:
            "Ollama Client - Chat with local LLMs — right inside your browser | Product Hunt"
        },
        items: {
          setup: {
            label: "Ollama Client Setup Guide",
            description: "Complete installation and configuration guide",
            badge: "Guide"
          },
          library: {
            label: "Official Ollama Model Library",
            description: "Browse available AI models and documentation",
            badge: "Library"
          },
          github: {
            label: "GitHub Repo",
            description: "Source code, releases, and contribution guidelines",
            badge: "Code"
          },
          faq: {
            label: "Troubleshooting & FAQ",
            description: "Common issues and community support",
            badge: "Help"
          }
        }
      },
      social: {
        github: "GitHub Page",
        portfolio: "Portfolio",
        linkedin: "LinkedIn",
        twitter: "Twitter",
        instagram: "Instagram",
        bug_report: "Report Bug / Feature"
      }
    }
  },
  hi: {
    translation: {
      common: {
        theme: {
          toggle: "थीम बदलें",
          toggle_aria_label: "थीम टॉगल करें",
          light: "लाइट",
          dark: "डार्क",
          system: "सिस्टम"
        },
        bug_report: {
          label: "बग",
          aria_label: "बग रिपोर्ट करें या सुविधा का अनुरोध करें",
          tooltip: "बग रिपोर्ट करें या सुविधा का अनुरोध करें"
        },
        settings: {
          label: "सेटिंग",
          aria_label: "एक्सटेंशन सेटिंग्स",
          tooltip: "एक्सटेंशन सेटिंग्स"
        },
        actions: {
          retry: "पुनः प्रयास करें",
          refresh: "रिफ्रेश करें"
        },
        social: {
          title: "मुझसे जुड़ें",
          visit_profile: "मेरी {{platform}} प्रोफाइल देखें"
        },
        language: {
          label: "भाषा",
          select_label: "इंटरफ़ेस भाषा",
          beta_badge: "बीटा",
          description: "इंटरफ़ेस के लिए अपनी पसंदीदा भाषा चुनें।",
          help_text:
            "अनुवाद AI द्वारा बनाए गए हैं। <0>GitHub</0> पर योगदान देकर हमें बेहतर बनाने में मदद करें!"
        }
      },
      selection_button: {
        label: "Ollama क्लाइंट से पूछें",
        tooltip: "Ollama क्लाइंट में जोड़ें"
      },
      welcome: {
        title: "Ollama चैट में आपका स्वागत है",
        subtitle: "स्थानीय AI बातचीत हुई आसान",
        start_chatting: "बातचीत शुरू करें",
        status: {
          connecting: {
            title: "कनेक्ट हो रहा है...",
            message: "Ollama सर्वर से कनेक्शन स्थापित कर रहा है"
          },
          connection_failed: {
            title: "कनेक्शन विफल",
            message: "Ollama से कनेक्ट होने में विफल। क्या सर्वर चल रहा है?"
          },
          no_models: {
            title: "कोई मॉडल नहीं मिला",
            message: "शुरू करने के लिए कृपया एक मॉडल पुल करें"
          },
          ready: {
            title: "चैट के लिए तैयार",
            message: "Ollama कनेक्टेड है और उपयोग के लिए तैयार है"
          }
        },
        setup_guide: {
          intro: "शुरू करने से पहले, इन त्वरित चरणों का पालन करें:",
          step1: "अपने सिस्टम पर <code>ollama</code> इंस्टॉल करें",
          step2: "<code>ollama run llama3</code> या कोई भी मॉडल चलाएँ",
          step3: "यहां वापस आएं और <b>रिफ्रेश</b> पर क्लिक करें",
          full_guide_link: "संपूर्ण सेटअप गाइड"
        },
        features: {
          private: {
            title: "100% प्राइवेट",
            description: "आपका डेटा स्थानीय रहता है"
          },
          offline: {
            title: "ऑफ़लाइन काम करता है",
            description: "इंटरनेट की आवश्यकता नहीं है"
          },
          local_processing: {
            title: "स्थानीय प्रोसेसिंग",
            description: "पूर्ण नियंत्रण"
          },
          embeddings: {
            title: "वेक्टर एम्बेडिंग",
            description: "सिमेंटिक खोज के लिए तैयार"
          }
        },
        performance_notice: {
          title: "⚠️ परफॉर्मेंस नोटिस",
          message:
            "यह एक्सटेंशन आपके स्थानीय Ollama सर्वर के लिए एक यूज़र इंटरफ़ेस है। प्रतिक्रिया समय और मॉडल आउटपुट गुणवत्ता पूरी तरह से आपके डिवाइस के हार्डवेयर (CPU, RAM, GPU) और आपके द्वारा उपयोग किए जा रहे विशिष्ट मॉडल पर निर्भर करती है। एक्सटेंशन द्वारा स्वयं कोई प्रोसेसिंग नहीं की जाती है।"
        }
      },
      chat: {
        input: {
          placeholder: "एक संदेश टाइप करें...",
          switch_model: "मॉडल बदलें",
          files_ready: "{{count}} फ़ाइलें तैयार हैं।",
          chars: "अक्षर",
          enter_to_send: "भेजें",
          enter_key: "एंटर"
        },
        actions: {
          copy: "कॉपी करें",
          copied: "कॉपी किया गया",
          regenerate: "पुनः जेनरेट करें",
          switch_model_tooltip: "मॉडल बदलें"
        },
        metrics: {
          title: "परफॉर्मेंस मेट्रिक्स",
          toggle_aria_label: "मेट्रिक्स टॉगल करें",
          toggle_title: "मेट्रिक्स टॉगल करें",
          total_time: "कुल समय",
          generation_speed: "जनरेशन गति",
          prompt_tokens: "प्रॉम्प्ट टोकन",
          generated_tokens: "जनरेट किए गए टोकन",
          load_time: "लोड समय",
          prompt_eval_time: "प्रॉम्प्ट मूल्यांकन समय"
        },
        search: {
          button_title: "चैट इतिहास खोजें (सिमेंटिक खोज)",
          button_label: "चैट खोजें",
          dialog_title: "सिमेंटिक चैट खोज",
          dialog_description:
            "केवल कीवर्ड द्वारा नहीं, बल्कि अर्थ द्वारा अपना चैट इतिहास खोजें",
          beta_badge: "बीटा v0.3.0",
          placeholder: "अर्थ के अनुसार बातचीत खोजें...",
          scope_all: "सभी चैट",
          scope_current: "वर्तमान चैट",
          searching: "चैट इतिहास खोजा जा रहा है...",
          no_results: "कोई परिणाम नहीं मिला। कोई भिन्न खोज क्वेरी आज़माएँ।",
          start_typing:
            "सिमेंटिक रूप से अपना चैट इतिहास खोजने के लिए टाइप करना शुरू करें...",
          result_badge: "परिणाम",
          results_badge: "परिणाम",
          match_percentage: "% मिलान",
          role_you: "आप",
          role_assistant: "सहायक",
          unknown_session: "अज्ञात सेशन",
          time_just_now: "अभी-अभी",
          time_minute: "मिनट",
          time_minutes: "मिनट",
          time_hour: "घंटा",
          time_hours: "घंटे",
          time_day: "दिन",
          time_days: "दिन",
          time_ago: "पहले",
          time_unknown: "अज्ञात समय"
        },
        backfill: {
          title: "चैट इतिहास बैकफ़िल करें",
          description:
            "सिमेंटिक खोज को सक्षम करने के लिए सभी मौजूदा चैट संदेशों के लिए एम्बेडिंग जेनरेट करें",
          error_label: "त्रुटि",
          completed_label: "पूरा हुआ!",
          completed_message:
            "सफलतापूर्वक {{count}} सेशन में {{current}} संदेशों को एम्बेड किया गया।",
          processing_label:
            "{{total}} संदेशों में से {{current}} को प्रोसेस किया जा रहा है",
          info_sessions: "• यह {{count}} {{sessions}} के सभी संदेशों को प्रोसेस करेगा",
          session_singular: "सेशन",
          session_plural: "सेशन",
          info_min_chars:
            "• केवल 10 से अधिक अक्षरों वाले संदेशों को ही एम्बेड किया जाएगा",
          info_time_warning: "• संदेशों की संख्या के आधार पर इसमें कुछ समय लग सकता है",
          button_processing: "प्रोसेस किया जा रहा है...",
          button_start: "बैकफ़िल शुरू करें",
          button_completed: "बैकफ़िल पूरा हुआ"
        },
        send: {
          send_message: "संदेश भेजें",
          stop_generation: "जनरेशन रोकें"
        },
        speech: {
          loading_voices: "वॉयस लोड हो रही हैं...",
          stop_speaking: "बोलना बंद करें",
          speak_message: "संदेश बोलें"
        },
        voice_selector: {
          select_voice: "वॉयस चुनें",
          select_placeholder: "एक वॉयस चुनें...",
          search_placeholder: "नाम, भाषा, या URI द्वारा खोजें...",
          no_voices_found: "कोई वॉयस नहीं मिली",
          no_voices_available: "इस डिवाइस पर कोई वॉयस उपलब्ध नहीं है",
          try_different_search: "कोई भिन्न खोज शब्द आज़माएँ",
          network_voice: "नेटवर्क वॉयस",
          default_badge: "डिफ़ॉल्ट",
          unknown_language: "अज्ञात"
        },
        message: {
          loading: "लोड हो रहा है..."
        }
      },
      file_upload: {
        button: {
          aria_label: "फ़ाइल अपलोड करें",
          tooltip: "फ़ाइल अपलोड करें (PDF, DOCX, टेक्स्ट फ़ाइलें)"
        },
        preview: {
          remove_aria_label: "फ़ाइल हटाएँ",
          generating_embeddings: "एम्बेडिंग जेनरेट हो रही है...",
          extracting_pdf: "PDF से टेक्स्ट निकाला जा रहा है...",
          processing_docx: "DOCX दस्तावेज़ प्रोसेस किया जा रहा है...",
          processing_file: "फ़ाइल प्रोसेस की जा रही है..."
        },
        area: {
          files_ready: "{{count}} फ़ाइल तैयार",
          files_ready_plural: "{{count}} फ़ाइलें तैयार"
        },
        settings: {
          max_file_size_label: "अधिकतम फ़ाइल साइज़ (MB)",
          max_file_size_description:
            "व्यक्तिगत फ़ाइलों के लिए अधिकतम अनुमत साइज़। बड़ी फ़ाइलों को प्रोसेस होने में अधिक समय लग सकता है।"
        }
      },
      model: {
        ollama_status: {
          checking: "Ollama स्थिति जाँच रहा है...",
          error: "Ollama पहुंच योग्य नहीं है",
          empty: "कोई मॉडल नहीं मिला",
          ready: "Ollama तैयार है"
        },
        embedding_status: {
          checking: "स्थिति जाँच रहा है...",
          downloading: "{{model}} डाउनलोड हो रहा है... {{progress}}",
          ready: "एम्बेडिंग मॉडल तैयार: {{model}}",
          missing: "मॉडल गुम है: {{model}}",
          checking_model: "एम्बेडिंग मॉडल जाँच रहा है...",
          required_for_rag: "RAG सुविधाओं के लिए एम्बेडिंग मॉडल आवश्यक है।",
          download_button: "मॉडल डाउनलोड करें"
        },
        menu: {
          select_placeholder: "मॉडल चुनें...",
          models_label: "मॉडल",
          refresh_aria_label: "मॉडल रिफ्रेश करें",
          refresh_tooltip: "मॉडल रिफ्रेश करें",
          search_placeholder: "मॉडल खोजें...",
          no_model_found: "कोई मॉडल नहीं मिला।"
        },
        version: {
          tooltip: "Ollama संस्करण: {{version}}"
        },
        site_overrides: {
          title: "साइट-विशिष्ट ओवरराइड",
          description:
            "रेगेक्स पैटर्न का उपयोग करके विशिष्ट साइटों के लिए कस्टम निष्कर्षण सेटिंग्स कॉन्फ़िगर करें",
          add_pattern_label: "साइट पैटर्न जोड़ें",
          pattern_placeholder: "medium.com या ^https://twitter\\.com/.*",
          pattern_empty_error: "साइट पैटर्न खाली नहीं हो सकता",
          pattern_exists_error: "साइट ओवरराइड पहले से मौजूद है",
          pattern_invalid_error: "अवैध नियमित अभिव्यक्ति पैटर्न",
          examples: "उदाहरण: {{example1}} या {{example2}}",
          active_overrides: "सक्रिय ओवरराइड",
          site_count: "{{count}} साइट",
          site_count_plural: "{{count}} साइटें",
          select_site_label: "कॉन्फ़िगर करने के लिए साइट चुनें",
          select_placeholder: "एक साइट चुनें...",
          search_placeholder: "साइट खोजें...",
          no_sites_found: "कोई साइट नहीं मिली।",
          no_overrides: "कोई साइट-विशिष्ट ओवरराइड कॉन्फ़िगर नहीं किया गया है",
          no_overrides_hint:
            "विशिष्ट साइटों के लिए निष्कर्षण सेटिंग्स को अनुकूलित करने के लिए पैटर्न जोड़ें",
          scroll_strategy_label: "स्क्रॉल रणनीति",
          scroll_depth_label: "स्क्रॉल गहराई",
          add_button: "जोड़ें"
        },
        exclude_urls: {
          title: "अपवर्जित URL",
          description:
            "रेगेक्स पैटर्न का उपयोग करके संवेदनशील पृष्ठों से एक्सटेंशन एक्सेस को ब्लॉक करें",
          add_pattern_label: "URL पैटर्न जोड़ें",
          pattern_placeholder: "^https://example\\.com/private.*",
          pattern_empty_error: "पैटर्न खाली नहीं हो सकता",
          pattern_exists_error: "पैटर्न पहले से मौजूद है",
          pattern_invalid_error: "अवैध नियमित अभिव्यक्ति पैटर्न",
          examples:
            "URL से मिलान करने के लिए नियमित अभिव्यक्तियों का उपयोग करें। उदाहरण: {{example1}} या {{example2}}",
          active_patterns: "सक्रिय पैटर्न",
          pattern_count: "{{count}} पैटर्न",
          pattern_count_plural: "{{count}} पैटर्न",
          no_patterns: "कोई URL पैटर्न कॉन्फ़िगर नहीं किया गया है",
          default_badge: "डिफ़ॉल्ट",
          add_button: "जोड़ें"
        },
        embedding_config: {
          storage_stats_title: "भंडारण आँकड़े",
          total_vectors: "कुल वेक्टर",
          storage_used: "उपयोग किया गया भंडारण",
          cache: "कैश",
          cache_entries: "{{size}} / {{maxSize}} एंट्री",
          database_management_title: "डेटाबेस प्रबंधन",
          database_management_description:
            "अपने वेक्टर एम्बेडिंग डेटाबेस को साफ करें और प्रबंधित करें",
          remove_duplicates_button: "डुप्लीकेट हटाएँ",
          remove_duplicates_description:
            "डुप्लीकेट एम्बेडिंग हटाएँ, प्रत्येक अद्वितीय संदेश की केवल पहली घटना रखें",
          clear_chat_button: "सभी चैट एम्बेडिंग साफ़ करें",
          clear_chat_description:
            "सभी चैट एम्बेडिंग हटाएँ। आप उन्हें बाद में पुनः जेनरेट करने के लिए बैकफ़िल कर सकते हैं",
          clear_all_button: "सभी एम्बेडिंग साफ़ करें",
          clear_all_description:
            "सभी एम्बेडिंग (चैट, फ़ाइलें, वेबपृष्ठ) हटाएँ। यह कार्रवाई पूर्ववत नहीं की जा सकती",
          chunking_title: "चंकिंग सेटिंग्स",
          chunking_description:
            "एम्बेडिंग के लिए टेक्स्ट को चंक्स में कैसे विभाजित किया जाता है, इसे कॉन्फ़िगर करें",
          chunk_size_label: "चंक्स साइज़ (टोकन)",
          chunk_size_description:
            "प्रति चंक टोकन की संख्या। बड़े चंक अधिक संदर्भ संरक्षित करते हैं लेकिन कम केंद्रित हो सकते हैं।",
          chunk_overlap_label: "चंक्स ओवरलैप (टोकन)",
          chunk_overlap_description:
            "चंक्स के बीच ओवरलैप। चंक सीमाओं के पार संदर्भ को संरक्षित करने में मदद करता है।",
          chunking_strategy_label: "चंकिंग रणनीति",
          chunking_strategy_description:
            "टेक्स्ट को चंक्स में कैसे विभाजित किया जाए। हाइब्रिड संदर्भ और फोकस का सबसे अच्छा संतुलन प्रदान करता है।",
          strategy_fixed: "निश्चित साइज़",
          strategy_semantic: "सिमेंटिक सीमाएँ",
          strategy_hybrid: "हाइब्रिड (अनुशंसित)",
          embedding_gen_title: "एम्बेडिंग जनरेशन",
          embedding_gen_description: "एम्बेडिंग जनरेशन परफॉर्मेंस कॉन्फ़िगर करें",
          batch_size_label: "बैच साइज़",
          batch_size_description:
            "समानांतर में एम्बेड करने के लिए टेक्स्ट की संख्या। उच्च मान तेज होते हैं लेकिन अधिक मेमोरी का उपयोग करते हैं।",
          enable_caching_label: "कैशिंग सक्षम करें",
          enable_caching_description:
            "पुनः जेनरेट करने से बचने के लिए समान सामग्री के लिए एम्बेडिंग कैश करें",
          use_webworker_label: "वेब वर्कर का उपयोग करें",
          use_webworker_description:
            "एम्बेडिंग जनरेशन को बैकग्राउंड थ्रेड पर ऑफ़लोड करें (अनुशंसित)",
          limits_title: "सीमाएँ और भंडारण",
          limits_description: "भंडारण सीमाएँ और सफाई नीतियां कॉन्फ़िगर करें",
          max_embeddings_label: "प्रति फ़ाइल अधिकतम एम्बेडिंग",
          max_embeddings_description:
            "प्रति फ़ाइल अधिकतम एम्बेडिंग (0 = असीमित)। बहुत बड़ी फ़ाइलों के साथ मेमोरी समस्याओं को रोकने में मदद करता है।",
          max_storage_label: "अधिकतम भंडारण साइज़ (MB)",
          max_storage_description:
            "MB में अधिकतम भंडारण साइज़ (0 = असीमित)। सीमा पूरी होने पर सबसे पुराने वेक्टर हटा दिए जाएंगे।",
          auto_cleanup_label: "स्वतः सफाई",
          auto_cleanup_description: "पुराने एम्बेडिंग को स्वचालित रूप से हटाएँ",
          cleanup_age_label: "सफाई अवधि (दिन)",
          cleanup_age_description: "इतने दिनों से पुराने एम्बेडिंग हटाएँ",
          chat_search_title: "चैट खोज सेटिंग्स",
          chat_search_description: "चैट इतिहास के लिए सिमेंटिक खोज कॉन्फ़िगर करें",
          auto_embed_label: "चैट संदेशों को स्वतः-एम्बेड करें",
          auto_embed_description:
            "सिमेंटिक खोज के लिए चैट संदेशों को स्वचालित रूप से एम्बेड करें (अनुशंसित)",
          backfill_title: "चैट इतिहास बैकफ़िल करें",
          backfill_description:
            "सिमेंटिक खोज को सक्षम करने के लिए सभी मौजूदा चैट संदेशों के लिए एम्बेडिंग जेनरेट करें",
          search_settings_title: "खोज सेटिंग्स",
          search_settings_description: "सिमेंटिक खोज के लिए डिफ़ॉल्ट पैरामीटर",
          search_limit_label: "डिफ़ॉल्ट खोज सीमा",
          search_limit_description:
            "सिमेंटिक खोज से लौटाए जाने वाले परिणामों की डिफ़ॉल्ट संख्या",
          min_similarity_label: "न्यूनतम समानता थ्रेशोल्ड",
          min_similarity_description:
            "न्यूनतम कोसाइन समानता स्कोर (0-1)। सिमेंटिक खोज के लिए, 0.4-0.6 अनुशंसित है। उच्च मान अधिक प्रासंगिक लेकिन कम परिणाम लौटाते हैं।",
          cache_ttl_label: "खोज कैश TTL (मिनट)",
          cache_ttl_description:
            "खोज परिणामों को कब तक कैश करना है (1-60 मिनट)। कैश की गई क्वेरी तुरंत लौटती है।",
          cache_max_size_label: "अधिकतम कैश की गई क्वेरी",
          cache_max_size_description:
            "कैश करने के लिए खोज क्वेरी की अधिकतम संख्या (10-200)। सीमा पूरी होने पर पुरानी एंट्री स्वचालित रूप से हटा दी जाती हैं।"
        }
      },
      prompts: {
        selector: {
          title: "प्रॉम्प्ट टेम्पलेट",
          description: "अपनी बातचीत को तुरंत शुरू करने के लिए {{count}} टेम्पलेट में से चुनें",
          search_placeholder: "टेम्पलेट, टैग, या विवरण खोजें...",
          sort_recent: "हाल का",
          sort_popular: "लोकप्रिय",
          sort_alphabetical: "A-Z",
          all_categories: "सभी श्रेणियां",
          no_templates_title: "कोई टेम्पलेट नहीं मिला",
          no_templates_search:
            "अपनी खोज या फ़िल्टर मानदंड समायोजित करने का प्रयास करें",
          no_templates_empty:
            "कोई प्रॉम्प्ट टेम्पलेट उपलब्ध नहीं है। सेटिंग्स में अपना पहला टेम्पलेट बनाएँ।",
          clear_filters: "फ़िल्टर साफ़ करें",
          preview_system_prompt: "सिस्टम प्रॉम्प्ट",
          preview_user_prompt: "उपयोगकर्ता प्रॉम्प्ट",
          preview_tags: "टैग",
          use_template: "टेम्पलेट का उपयोग करें",
          copy: "कॉपी करें"
        }
      },
      sessions: {
        selector: {
          title: "चैट सेशन",
          create_new: "नई चैट बनाएँ",
          create_new_aria: "नई चैट बनाएँ",
          start_new: "नई चैट शुरू करें",
          no_sessions: "अभी तक कोई चैट सेशन नहीं है",
          no_sessions_hint: "शुरू करने के लिए अपनी पहली चैट बनाएँ",
          session_count: "{{count}} सेशन",
          session_count_plural: "{{count}} सेशन"
        },
        delete: {
          aria_label: "चैट सेशन हटाएँ: {{title}}",
          tooltip: "चैट हटाएँ"
        },
        export: {
          tooltip: "चैट निर्यात करें",
          tooltip_all: "सभी चैट सेशन निर्यात करें",
          aria_label: "चैट निर्यात करें",
          aria_label_all: "सभी चैट सेशन निर्यात करें",
          format_json: "JSON",
          format_pdf: "PDF"
        },
        import: {
          tooltip: "चैट सेशन आयात करें",
          aria_label: "चैट सेशन आयात करें"
        }
      },
      tabs: {
        select: {
          placeholder: "खुले टैब चुनें"
        },
        toggle: {
          label_off: "टैब",
          label_on: "टैब+",
          tooltip: "खुले टैब के साथ इंटरैक्ट करें"
        }
      },
      settings: {
        content_extraction: {
          title: "सामग्री निष्कर्षण",
          description:
            "सभी वेबसाइटों के लिए डिफ़ॉल्ट सामग्री निष्कर्षण व्यवहार कॉन्फ़िगर करें।",
          enable: {
            label: "सामग्री निष्कर्षण की अनुमति दें",
            description: "लेज़ी लोडिंग समर्थन के साथ उन्नत सामग्री निष्कर्षण सक्षम करें"
          },
          selection_button: {
            label: 'चयन के बाद "Ollama क्लाइंट से पूछें" बटन दिखाएँ',
            description:
              "चैट में टेक्स्ट को तेज़ी से जोड़ने के लिए टेक्स्ट का चयन करते समय एक फ़्लोटिंग एक्शन बटन दिखाएँ"
          },
          scraper: {
            label: "सामग्री स्क्रैपर",
            auto: {
              label: "स्वतः",
              description: "स्मार्ट फ़ॉलबैक: Defuddle अधिक पठनीय हो जाता है",
              detail:
                "अधिकांश साइटों के लिए अच्छा है। बेहतर मार्कडाउन और कोड फ़ॉर्मेटिंग के लिए पहले Defuddle का उपयोग करता है, यदि आवश्यक हो तो Readability पर फ़ॉलबैक करता है।"
            },
            defuddle: {
              label: "Defuddle",
              description: "तकनीकी और अत्यधिक कोडित सामग्री",
              detail:
                "GitHub, दस्तावेज़ीकरण, Stack Overflow, और डेवलपर ब्लॉग के लिए सबसे अच्छा। कोड ब्लॉक और मार्कडाउन संरचना को संरक्षित करता है।"
            },
            readability: {
              label: "Readability",
              description: "लेख और ब्लॉग पोस्ट",
              detail:
                "समाचार लेख, Medium पोस्ट, और पारंपरिक ब्लॉग सामग्री के लिए उपयुक्त।"
            }
          },
          scroll_strategy: {
            label: "स्क्रॉल रणनीति",
            none: "सबसे तेज़ निष्कर्षण, लेज़ी लोडिंग समर्थित नहीं है",
            instant: "तेज स्क्रॉलिंग साधारण लेज़ी लोडिंग के लिए अच्छी तरह से काम करती है",
            gradual:
              "जानबूझकर रुकने और गति और सटीकता के मिश्रण के साथ संतुलित सहज स्क्रॉलिंग",
            smart: "गतिशील सामग्री-जागरूक स्मार्ट स्क्रॉलिंग",
            options: {
              none: "कोई स्क्रॉलिंग नहीं",
              instant: "तेज स्क्रॉलिंग",
              gradual: "क्रमिक स्क्रॉलिंग",
              smart: "स्मार्ट डिटेक्शन"
            },
            options_short: {
              none: "कोई नहीं",
              instant: "तेज",
              gradual: "क्रमिक",
              smart: "स्मार्ट"
            }
          },
          scroll_depth: {
            label: "स्क्रॉल गहराई",
            description:
              "स्क्रॉल करने के लिए पृष्ठ का प्रतिशत (उच्च = अधिक सामग्री, धीमी)"
          },
          timeout: {
            scroll_delay: "मिलीसेकंड में स्क्रॉल विलंब",
            mutation_timeout: "मिलीसेकंड में म्यूटेशन ऑब्जर्वर टाइमआउट",
            network_timeout: "मिलीसेकंड में नेटवर्क निष्क्रिय टाइमआउट",
            max_wait: "अधिकतम प्रतीक्षा समय (मिलीसेकंड)"
          },
          badges: {
            recommended: "अनुशंसित",
            active: "सक्रिय"
          }
        },
        model: {
          title: "मॉडल सेटिंग्स",
          description: "इष्टतम प्रदर्शन के लिए पैरामीटर कॉन्फ़िगर करें।",
          configuration_title: "मॉडल कॉन्फ़िगरेशन",
          configuration_description: "अपने AI मॉडल पैरामीटर कॉन्फ़िगर करें।",
          system: {
            title: "सिस्टम कॉन्फ़िगरेशन",
            description:
              "मॉडल व्यवहार को नियंत्रित करने के लिए सिस्टम प्रॉम्प्ट और स्टॉप अनुक्रम कॉन्फ़िगर करें।",
            prompt_label: "सिस्टम प्रॉम्प्ट",
            prompt_placeholder:
              "मॉडल के व्यवहार को निर्देशित करने के लिए एक कस्टम सिस्टम प्रॉम्प्ट दर्ज करें...",
            stop_sequences_label: "स्टॉप अनुक्रम",
            stop_sequence_placeholder: "स्टॉप अनुक्रम दर्ज करें...",
            add_button: "जोड़ें"
          },
          sampling: {
            title: "सैंपलिंग पैरामीटर",
            description: "रैंडमनेस और टोकन चयन को नियंत्रित करें।"
          },
          context: {
            title: "संदर्भ और जनरेशन",
            description: "मेमोरी और आउटपुट नियंत्रण सेटिंग्स"
          },
          parameters: {
            temperature: {
              label: "तापमान",
              conservative: "रूढ़िवादी",
              creative: "रचनात्मक"
            },
            top_p: {
              label: "Top-p (न्यूक्लियस)",
              focused: "केंद्रित",
              diverse: "विविध"
            },
            top_k: {
              label: "Top-k",
              validation_min: "कम से कम {{min}} होना चाहिए"
            },
            min_p: {
              label: "Min-p",
              validation_min: "कम से कम {{min}} होना चाहिए।",
              validation_max: "अधिकतम {{max}} होना चाहिए।"
            },
            seed: {
              label: "सीड",
              validation_min: "कम से कम {{min}} होना चाहिए"
            },
            num_ctx: {
              label: "संदर्भ साइज़",
              validation_min: "कम से कम {{min}} होना चाहिए"
            },
            num_predict: {
              label: "अधिकतम टोकन",
              validation_min: "कम से कम {{min}} होना चाहिए।"
            },
            repeat_penalty: {
              label: "दोहराव दंड",
              validation_min: "{{min}} से अधिक होना चाहिए।"
            },
            repeat_last_n: {
              label: "पिछले N दोहराएँ",
              validation_min: "कम से कम {{min}} होना चाहिए।"
            }
          }
        },
        base_url: {
          title: "Ollama बेस URL",
          description: "अपने Ollama इंस्टॉलेशन के लिए सर्वर एंडपॉइंट कॉन्फ़िगर करें।",
          label: "Ollama API सर्वर एंडपॉइंट",
          error_invalid_url: "कृपया एक वैध URL दर्ज करें।",
          status_local: "स्थानीय सर्वर कनेक्शन",
          status_remote: "रिमोट सर्वर कनेक्शन",
          badges: {
            default: "डिफ़ॉल्ट",
            remote: "रिमोट"
          },
          button: {
            save: "सेव करें",
            saving: "सेव कर रहा है",
            saved: "सेव किया गया"
          }
        },
        model_pull: {
          title: "मॉडल लाइब्रेरी",
          description: "अपनी परियोजनाओं के लिए AI मॉडल ब्राउज़ करें और डाउनलोड करें।",
          search_placeholder: "नाम या विवरण द्वारा मॉडल खोजें...",
          status: {
            cancelled: "रद्द किया गया",
            downloading: "मॉडल डाउनलोड हो रहा है",
            loading_models: "मॉडल लोड हो रहे हैं...",
            no_models: "कोई मॉडल नहीं मिला",
            adjust_search: "अपने खोज शब्दों को समायोजित करें।"
          },
          button: {
            variants: "वेरिएंट",
            loading: "लोड हो रहा है",
            pulling: "पुल कर रहा है"
          },
          variants_label: "उपलब्ध वेरिएंट"
        },
        model_list: {
          unknown_size: "अज्ञात साइज़",
          invalid_size: "अवैध साइज़",
          unknown_date: "अज्ञात तिथि",
          invalid_date: "अवैध तिथि",
          time_ago_hours: "{{count}} घंटे पहले",
          time_ago_days: "{{count}} दिन पहले",
          title: "मॉडल",
          title_count: "{{count}} मॉडल",
          retry: "पुनः प्रयास करें",
          refresh: "रिफ्रेश करें",
          no_models: "कोई मॉडल नहीं मिला",
          refresh_tooltip: "मॉडल रिफ्रेश करें",
          delete_dialog: {
            title: "इस मॉडल को हटाएँ?",
            description:
              "यह कार्रवाई पूर्ववत नहीं की जा सकती। मॉडल को आपके स्थानीय सिस्टम से स्थायी रूप से हटा दिया जाएगा।",
            cancel: "रद्द करें",
            confirm: "हटाएँ"
          }
        },
        model_info: {
          title: "मॉडल जानकारी",
          no_data: "इस मॉडल के लिए कोई डेटा उपलब्ध नहीं है।",
          no_data_available: "कोई मॉडल डेटा उपलब्ध नहीं है",
          error_fetching: "मॉडल डेटा लाने में त्रुटि।",
          error_details: "मॉडल विवरण प्राप्त नहीं कर सका।",
          refresh_tooltip: "मॉडल विवरण रिफ्रेश करें",
          capabilities: "क्षमताएँ",
          technical_details: "तकनीकी विवरण",
          unknown_file_type: "अज्ञात"
        },
        loaded_models: {
          title: "लोड किए गए मॉडल",
          count_one: "{{count}} मॉडल",
          count_other: "{{count}} मॉडल",
          refresh_tooltip: "लोड किए गए मॉडल रिफ्रेश करें",
          no_models_title: "मेमोरी में वर्तमान में कोई मॉडल लोड नहीं है",
          no_models_description: "लोड होने पर मॉडल यहां दिखाई देंगे।",
          unload_tooltip: "मॉडल अनलोड करें"
        },
        tabs: {
          general: "सामान्य",
          prompts: "प्रॉम्प्ट",
          models: "मॉडल",
          extraction: "निष्कर्षण",
          embeddings: "एम्बेडिंग",
          voices: "वॉयस",
          reset: "रीसेट करें",
          guides: "गाइड"
        },
        page: {
          title: "Ollama क्लाइंट सेटिंग्स",
          description:
            "अपने Ollama सेटअप के सभी पहलुओं को एक ही स्थान पर प्रबंधित करें। युक्तियों और सेटअप मार्गदर्शन के लिए, गाइड टैब पर जाएँ।"
        },
        speech: {
          title: "स्पीच सेटिंग्स",
          description: "अपने टेक्स्ट-टू-स्पीच वॉयस, गति, और टोन सेटिंग्स कॉन्फ़िगर करें।",
          voice_label: "वॉयस",
          rate_label: "स्पीच गति",
          pitch_label: "वॉयस पिच",
          preview_title: "पूर्वावलोकन",
          test_text_label: "परीक्षण टेक्स्ट",
          test_text_placeholder: "यहां टाइप करके अपनी वॉयस सेटिंग्स का परीक्षण करें...",
          test_hint_text: 'अपना टेक्स्ट सुनने के लिए "वॉयस का परीक्षण करें" पर क्लिक करें।',
          test_hint_default:
            'डिफ़ॉल्ट सैंपल सुनने के लिए "वॉयस का परीक्षण करें" पर क्लिक करें।',
          test_button: "वॉयस का परीक्षण करें",
          test_fallback: "नमस्ते, यह आपकी स्पीच सेटिंग्स का एक परीक्षण है।",
          rate: {
            very_slow: "बहुत धीमी",
            slow: "धीमी",
            normal: "सामान्य",
            fast: "तेज",
            very_fast: "बहुत तेज"
          },
          pitch: {
            very_low: "बहुत कम",
            low: "कम",
            normal: "सामान्य",
            high: "उच्च",
            very_high: "बहुत उच्च"
          }
        },
        embeddings: {
          title: "वेक्टर एम्बेडिंग",
          beta_badge: "बीटा",
          description:
            "एम्बेडिंग फ़ाइल अपलोड और चैट इतिहास के लिए सिमेंटिक खोज, पुनर्प्राप्ति संवर्धित जनरेशन, और संदर्भ-जागरूक सुविधाओं को सक्षम करती है।",
          model_label: "एम्बेडिंग मॉडल",
          status: {
            installed: "स्थापित",
            not_found: "नहीं मिला",
            checking: "जाँच रहा है...",
            check_button: "स्थिति जाँचें"
          },
          not_loaded: {
            title: "एम्बेडिंग मॉडल लोड नहीं हुआ",
            description:
              "सिमेंटिक खोज, RAG (पुनर्प्राप्ति संवर्धित जनरेशन), और संदर्भ-जागरूक सुविधाओं के लिए एम्बेडिंग मॉडल आवश्यक है। बेहतर संदर्भ समझ और फ़ाइल खोज क्षमताओं के साथ अपने चैट अनुभव को बढ़ाने के लिए इसे अभी डाउनलोड करें।",
            download_button: "मॉडल डाउनलोड करें"
          },
          downloading: {
            title: "मॉडल डाउनलोड हो रहा है..."
          },
          success: {
            title: "डाउनलोड सफल",
            description:
              "एम्बेडिंग मॉडल अब उपयोग के लिए तैयार है। अब आप सिमेंटिक खोज और संदर्भ-जागरूक सुविधाओं के साथ उन्नत चैट अनुभवों का आनंद ले सकते हैं।"
          },
          auto_downloaded: {
            title: "स्वतः-स्थापित",
            description:
              "एक्सटेंशन इंस्टॉल करने पर एम्बेडिंग मॉडल स्वचालित रूप से डाउनलोड हो गया था।"
          },
          test_generation: {
            title: "एम्बेडिंग जनरेशन का परीक्षण करें",
            description:
              "यह सत्यापित करने के लिए कि एम्बेडिंग मॉडल सही ढंग से काम कर रहा है, एक परीक्षण एम्बेडिंग जेनरेट करें।",
            button: "परीक्षण करें",
            button_testing: "परीक्षण कर रहा है..."
          },
          test_search: {
            title: "सिमेंटिक खोज",
            description:
              "सत्यापित करें कि आपकी अपलोड की गई फ़ाइलें सुलभ और खोज योग्य हैं। मिलान वाली सामग्री खोजने के लिए एक खोज क्वेरी दर्ज करें।",
            placeholder: "खोज...",
            results_found: "{{count}} परिणाम मिले",
            no_results:
              "कोई परिणाम नहीं मिला। कोई भिन्न खोज आज़माएँ या अधिक सामग्री अपलोड करें।"
          },
          what_are_embeddings: {
            title: "एम्बेडिंग क्या हैं?",
            point_1:
              "सिमेंटिक अर्थ को कैप्चर करने वाले संख्यात्मक वैक्टर में टेक्स्ट को रूपांतरित करें",
            point_2: "आपके चैट इतिहास और अपलोड की गई फ़ाइलों में सिमेंटिक खोज सक्षम करें",
            point_3: "संदर्भ-जागरूक प्रतिक्रियाओं के लिए RAG को शक्ति प्रदान करें",
            point_4:
              "AI प्रतिक्रियाओं को बेहतर बनाने के लिए आपकी फ़ाइलों से प्रासंगिक संदर्भ प्रदान करें"
          },
          rag_mode: {
            label: "स्मार्ट संदर्भ (RAG)",
            description:
              "संपूर्ण फ़ाइल सामग्री भेजने के बजाय अपनी फ़ाइलों से प्रासंगिक संदर्भ खोजने के लिए सिमेंटिक खोज का उपयोग करें।"
          },
          model_select: {
            label: "एम्बेडिंग मॉडल",
            placeholder: "एक मॉडल चुनें",
            description:
              "एम्बेडिंग जेनरेट करने के लिए एक मॉडल चुनें। आपको इसे पहले डाउनलोड करने की आवश्यकता हो सकती है।"
          }
        },
        prompts: {
          title: "प्रॉम्प्ट टेम्पलेट",
          description: "अपने {{count}} प्रॉम्प्ट टेम्पलेट के संग्रह को प्रबंधित करें।",
          export: "टेम्पलेट निर्यात करें",
          import: "टेम्पलेट आयात करें",
          reset: "डिफ़ॉल्ट पर रीसेट करें",
          reset_dialog: {
            title: "टेम्पलेट को डिफ़ॉल्ट पर रीसेट करें?",
            description:
              "यह आपके सभी वर्तमान टेम्पलेट को डिफ़ॉल्ट वाले से बदल देगा। यह कार्रवाई पूर्ववत नहीं की जा सकती।",
            cancel: "रद्द करें",
            confirm: "टेम्पलेट रीसेट करें"
          },
          search_placeholder: "टेम्पलेट खोजें...",
          category_placeholder: "श्रेणी",
          all_categories: "सभी श्रेणियां",
          sort: {
            recent: "हाल का",
            popular: "लोकप्रिय",
            alphabetical: "A-Z"
          },
          new_template: "नया टेम्पलेट",
          form: {
            title: "शीर्षक",
            title_placeholder: "टेम्पलेट शीर्षक",
            category: "श्रेणी",
            category_placeholder: "उदाहरण के लिए, डेवलपमेंट, लेखन",
            description: "विवरण",
            description_placeholder:
              "टेम्पलेट के उद्देश्य और कार्यक्षमता का संक्षिप्त विवरण।",
            tags: "टैग",
            tags_placeholder: "टैग1, टैग2, टैग3",
            user_prompt: "उपयोगकर्ता प्रॉम्प्ट",
            user_prompt_placeholder: "मुख्य प्रॉम्प्ट टेम्पलेट",
            system_prompt: "सिस्टम प्रॉम्प्ट",
            create_button: "टेम्पलेट बनाएँ"
          },
          delete_dialog: {
            title: "टेम्पलेट हटाएँ",
            description:
              'क्या आप "{{title}}" हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती।',
            cancel: "रद्द करें",
            confirm: "हटाएँ"
          },
          created_at: "बनाया गया {{date}}",
          used_times: "{{count}} बार उपयोग किया गया"
        },
        reset: {
          title: "सेटिंग रीसेट करें",
          description:
            "मॉड्यूल द्वारा संग्रहीत डेटा साफ़ करें या सब कुछ डिफ़ॉल्ट पर रीसेट करें",
          danger_zone: {
            title: "डेंजर ज़ोन",
            description: "यह सभी डेटा साफ़ कर देगा और पूर्ववत नहीं किया जा सकता",
            button: "सभी रीसेट करें"
          },
          dialog: {
            title: "रीसेट की पुष्टि करें",
            description: "यह सभी डेटा साफ़ कर देगा और पूर्ववत नहीं किया जा सकता।",
            confirm: "हाँ, सभी रीसेट करें",
            cancel: "रद्द करें"
          },
          modules: {
            ollama: {
              description: "मॉडल सेटिंग्स और कॉन्फ़िगरेशन"
            },
            theme: {
              description: "UI स्वरूपण प्राथमिकताएँ"
            },
            browser: {
              description: "टैब एक्सेस और URL पैटर्न"
            },
            tts: {
              description: "टेक्स्ट-टू-स्पीच सेटिंग्स"
            },
            chat_sessions: {
              description: "बातचीत का इतिहास"
            },
            default: {
              description: "मॉड्यूल सेटिंग्स"
            }
          },
          item_count: "{{count}} आइटम",
          item_count_plural: "{{count}} आइटम",
          reset_button: "रीसेट करें"
        }
      },
      guides: {
        title: "सहायक गाइड और दस्तावेज़ीकरण",
        description:
          "Ollama क्लाइंट सेट अप करने या सुविधाओं को खोजने में सहायता चाहिए? इन उपयोगी संसाधनों को देखें",
        support: {
          title: "परियोजना का समर्थन करें",
          description:
            "Product Hunt पर Ollama क्लाइंट को प्रदर्शित करके हमें विकसित होने में मदद करें",
          image_alt:
            "Ollama क्लाइंट - स्थानीय LLM के साथ चैट करें — ठीक अपने ब्राउज़र के अंदर | Product Hunt"
        },
        items: {
          setup: {
            label: "Ollama क्लाइंट सेटअप गाइड",
            description: "पूर्ण इंस्टॉलेशन और कॉन्फ़िगरेशन गाइड",
            badge: "गाइड"
          },
          library: {
            label: "आधिकारिक Ollama मॉडल लाइब्रेरी",
            description: "उपलब्ध AI मॉडल और दस्तावेज़ीकरण ब्राउज़ करें",
            badge: "लाइब्रेरी"
          },
          github: {
            label: "GitHub रेपो",
            description: "स्रोत कोड, रिलीज़, और योगदान दिशानिर्देश",
            badge: "कोड"
          },
          faq: {
            label: "समस्या निवारण और FAQ",
            description: "सामान्य समस्याएँ और सामुदायिक समर्थन",
            badge: "सहायता"
          }
        }
      },
      social: {
        github: "GitHub पेज",
        portfolio: "पोर्टफोलियो",
        linkedin: "LinkedIn",
        twitter: "Twitter",
        instagram: "Instagram",
        bug_report: "बग / सुविधा रिपोर्ट करें"
      }
    }
  }
} as const
