// This file is auto-generated by tools/generate-i18n-resources.ts
// Do not edit this file directly

import { useStorage } from "@plasmohq/storage/hook"
import { STORAGE_KEYS } from "@/lib/constants"
import { plasmoGlobalStorage } from "@/lib/plasmo-global-storage"

const translations: Record<string, Record<string, string>> = {
  de: {
    "selection_button.label": "Lokalen LLM fragen",
    "selection_button.tooltip": "Zum Local LLM Client hinzufügen"
  },
  en: {
    "selection_button.label": "Ask Local LLM",
    "selection_button.tooltip": "Add to Local LLM Client"
  },
  es: {
    "selection_button.label": "Preguntar al LLM local",
    "selection_button.tooltip": "Añadir al cliente LLM local"
  },
  fr: {
    "selection_button.label": "Demander au LLM local",
    "selection_button.tooltip": "Ajouter au client LLM local"
  },
  hi: {
    "selection_button.label": "स्थानीय LLM से पूछें",
    "selection_button.tooltip": "स्थानीय LLM क्लाइंट में जोड़ें"
  },
  it: {
    "selection_button.label": "Chiedi al LLM locale",
    "selection_button.tooltip": "Aggiungi al client LLM locale"
  },
  ja: {
    "selection_button.label": "ローカルLLMに聞く",
    "selection_button.tooltip": "ローカルLLMクライアントに追加"
  },
  ru: {
    "selection_button.label": "Спросить локальный LLM",
    "selection_button.tooltip": "Добавить в локальный LLM клиент"
  },
  zh: {
    "selection_button.label": "询问本地 LLM",
    "selection_button.tooltip": "添加到本地 LLM 客户端"
  }
}

export const useLiteTranslation = () => {
  const [lang] = useStorage<string>({
    key: STORAGE_KEYS.LANGUAGE,
    instance: plasmoGlobalStorage
  })

  const t = (key: string) => {
    const language = lang || "en"
    let targetLang = language

    // Simple fallback logic
    if (!translations[targetLang]) {
      if (typeof targetLang === "string") {
        if (targetLang.startsWith("zh")) targetLang = "zh"
        else if (targetLang.startsWith("fr")) targetLang = "fr"
        else targetLang = "en"
      } else {
        targetLang = "en"
      }
    }

    // Safety check if language still not found
    if (!translations[targetLang]) {
      targetLang = "en"
    }

    return translations[targetLang]?.[key] || translations.en?.[key] || key
  }

  return { t }
}
