import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const LOCALES_DIR = path.join(__dirname, "../src/locales")
const OUTPUT_FILE = path.join(__dirname, "../src/i18n/resources.ts")
const CHROME_LOCALES_DIR = path.join(__dirname, "../public/_locales")
const CHROME_LOCALE_MAP: Record<string, string> = {
  zh: "zh_CN"
}

type ExtensionMessages = {
  name: string
  short_name: string
  description: string
  action_default_title: string
}

type TranslationJson = {
  extension?: Partial<ExtensionMessages>
  [key: string]: unknown
}

function assertExtensionMessages(
  locale: string,
  extension: TranslationJson["extension"]
): asserts extension is ExtensionMessages {
  const requiredKeys = [
    "name",
    "short_name",
    "description",
    "action_default_title"
  ] satisfies Array<keyof ExtensionMessages>

  const missingKeys = requiredKeys.filter((key) => !extension?.[key])

  if (missingKeys.length > 0) {
    throw new Error(
      `${locale}/translation.json is missing extension metadata: ${missingKeys.join(", ")}`
    )
  }
}

function toChromeMessages(extension: ExtensionMessages) {
  return {
    extName: {
      message: extension.name,
      description: "Extension name shown by Chrome and Chrome Web Store"
    },
    extShortName: {
      message: extension.short_name,
      description: "Short extension name"
    },
    extDescription: {
      message: extension.description,
      description: "Extension description shown by Chrome and Chrome Web Store"
    },
    actionDefaultTitle: {
      message: extension.action_default_title,
      description: "Toolbar action title"
    }
  }
}

function resetChromeLocalesDir() {
  fs.rmSync(CHROME_LOCALES_DIR, { recursive: true, force: true })
  fs.mkdirSync(CHROME_LOCALES_DIR, { recursive: true })
}

async function generateResources() {
  console.log("📦 Generating i18n resources...")

  const resources: Record<string, { translation: unknown }> = {}
  const chromeMessages: Record<string, ReturnType<typeof toChromeMessages>> = {}
  let hasErrors = false

  if (!fs.existsSync(LOCALES_DIR)) {
    console.error(`❌ Locales directory not found: ${LOCALES_DIR}`)
    process.exit(1)
  }

  const locales = fs.readdirSync(LOCALES_DIR).filter((item) => {
    return fs.statSync(path.join(LOCALES_DIR, item)).isDirectory()
  })

  for (const locale of locales) {
    const translationFile = path.join(LOCALES_DIR, locale, "translation.json")

    if (fs.existsSync(translationFile)) {
      try {
        const content = fs.readFileSync(translationFile, "utf-8")
        const json = JSON.parse(content) as TranslationJson
        assertExtensionMessages(locale, json.extension)
        resources[locale] = { translation: json }
        chromeMessages[CHROME_LOCALE_MAP[locale] ?? locale] = toChromeMessages(
          json.extension
        )
        console.log(`  ✓ Loaded ${locale}`)
      } catch (error) {
        console.error(`  ❌ Error loading ${locale}:`, error)
        hasErrors = true
      }
    }
  }

  if (hasErrors) {
    process.exit(1)
  }

  const fileContent = `// This file is auto-generated by tools/generate-i18n-resources.ts
// Do not edit this file directly

export const resources = ${JSON.stringify(resources, null, 2)} as const;
`

  fs.writeFileSync(OUTPUT_FILE, fileContent)
  console.log(`✨ Generated resources at ${OUTPUT_FILE}`)

  resetChromeLocalesDir()
  for (const [locale, messages] of Object.entries(chromeMessages)) {
    const localeDir = path.join(CHROME_LOCALES_DIR, locale)
    fs.mkdirSync(localeDir, { recursive: true })
    fs.writeFileSync(
      path.join(localeDir, "messages.json"),
      `${JSON.stringify(messages, null, 2)}\n`
    )
    console.log(`✨ Generated Chrome locale metadata for ${locale}`)
  }

  try {
    console.log("💅 Formatting with Biome...")
    const { execSync } = await import("child_process")
    // --vcs-use-ignore-file=false so biome will touch the file even though it is .gitignored
    execSync(
      `npx biome check --write --vcs-use-ignore-file=false "${OUTPUT_FILE}" "${CHROME_LOCALES_DIR}"`,
      { stdio: "inherit" }
    )
    console.log("✅ Formatting complete")
  } catch (error) {
    console.error("⚠️ Failed to format generated file:", error)
  }
}

generateResources()
