import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const LOCALES_DIR = path.join(__dirname, "../src/locales")
const OUTPUT_FILE = path.join(__dirname, "../src/i18n/resources.ts")

async function generateResources() {
  console.log("📦 Generating i18n resources...")

  const resources: Record<string, any> = {}
  
  if (!fs.existsSync(LOCALES_DIR)) {
    console.error(`❌ Locales directory not found: ${LOCALES_DIR}`)
    process.exit(1)
  }

  const locales = fs.readdirSync(LOCALES_DIR).filter(item => {
    return fs.statSync(path.join(LOCALES_DIR, item)).isDirectory()
  })

  for (const locale of locales) {
    const translationFile = path.join(LOCALES_DIR, locale, "translation.json")
    
    if (fs.existsSync(translationFile)) {
      try {
        const content = fs.readFileSync(translationFile, "utf-8")
        const json = JSON.parse(content)
        resources[locale] = {
          translation: json
        }
        console.log(`  ✓ Loaded ${locale}`)
      } catch (error) {
        console.error(`  ❌ Error loading ${locale}:`, error)
      }
    }
  }

  const fileContent = `// This file is auto-generated by tools/generate-i18n-resources.ts
// Do not edit this file directly

export const resources = ${JSON.stringify(resources, null, 2)} as const;
`

  fs.writeFileSync(OUTPUT_FILE, fileContent)
  console.log(`✨ Generated resources at ${OUTPUT_FILE}`)

  try {
    console.log("💅 Formatting with Biome...")
    const { execSync } = await import("child_process")
    execSync(`npx biome check --write "${OUTPUT_FILE}"`, { stdio: "inherit" })
    console.log("✅ Formatting complete")
  } catch (error) {
    console.error("⚠️ Failed to format generated file:", error)
  }
}

generateResources()
